{ ... }:
{
  imports = [
    ./bootloader.nix
    ./clamav-scanner.nix
    ./dns.nix
    ./fonts.nix
    ./firewall.nix
    ./gc.nix
    #./gnome.nix
    ./hardware.nix
    ./international.nix
    ./linux-kernel.nix
    ./langauge-servers.nix
    #./mac-random.nix
    ./nvidia.nix
    ./networking.nix
    ./programs.nix
    ./security.nix
    ./services.nix
    ./sound.nix
    ./stylix.nix
    ./system.nix
    ./time.nix
    ./virtualisation.nix
    ./xdg.nix
    ./screen.nix
    ./rust.nix
    ./swap.nix
    ./security-services.nix
    ./terminal-utils.nix
    ./theme.nix
    ./usb.nix
    ./utils.nix
    ./wasm.nix
    #./vpn.nix
    ./work.nix
    #./yubikey.nix
  ];
}
