{ ... }:
{
  imports = [
    ./alpha.nix
    ./auto-session.nix
    ./autoclose.nix
    ./barbar.nix
    ./bufferline.nix
    ./cmp.nix
    ./comment.nix
    ./copilot.nix
    ./cursorline.nix
    ./dressing.nix
    ./extralua.nix
    ./fidget.nix
    ./friendly-snippets.nix
    ./gitignore.nix
    ./gitsigns.nix
    ./harpoon.nix
    ./helm.nix
    ./indent-blankline.nix
    ./lsp.nix
    ./luasnip.nix
    ./lualine.nix
    ./markdown-preview.nix
    ./mini.nix
    ./neo-tree.nix
    ./noice.nix
    ./neorg.nix
    ./none-ls.nix
    ./notify.nix
    ./oil.nix
    ./ollama.nix
    ./spectre.nix
    ./telescope.nix
    ./tmux-navigator.nix
    ./todo-comments.nix
    ./treesitter.nix
    ./which-key.nix
    ./wilder.nix
  ];
}

